### ISSUE TITLE
无法将题目传输到Sublime

### ISSUE THREAD

**Issue by AshDr** [CodeforcesContestHelper/CCHv2#100]
Sublime版本：4152
os：Windows 11
所参考的配置教程为知乎上的[教程](https://zhuanlan.zhihu.com/p/407169892)
点击传送题目后没有文件夹和对应cpp文件生成
点击后的端口信息如下：
![image](https://github.com/CodeforcesContestHelper/CCHv2/assets/56424714/afe7c93d-b2f6-483a-b7f1-5963edce4e3b)

另外通过数据似乎也无法查看

**Comment by tiger2005** [comment]
请检查是否在 CCHv2 加入 12345 的端口。

**Comment by AshDr** [comment]
> 请检查是否在 CCHv2 加入 12345 的端口。
有将12345加入到transform port设置中

**Comment by AshDr** [comment]
> 请检查是否在 CCHv2 加入 12345 的端口。

确认有将12345加入到Transform Port中

**Comment by AshDr** [comment]
如下报错信息
![image](https://github.com/CodeforcesContestHelper/CCHv2/assets/56424714/44bfa6f8-971f-4e6f-8ffb-89e2860f90df)

**Comment by tiger2005** [comment]
能给一下题号吗

**Comment by tiger2005** [comment]
这个问题应该就是 CF 题目里面出现了奇怪的字符，可能得加一些 filter

**Comment by tiger2005** [comment]
把 sublime text 插件中 24 行的 \xFF 改成 \x7F 试试？

**Comment by AshDr** [comment]
> 这个问题应该就是 CF 题目里面出现了奇怪的字符，可能得加一些 filter

貌似不是某个问题 是在send整场problems的时候出现的问题。我现在不在宿舍，等晚上回去试试

**Comment by tiger2005** [comment]
比赛场次是什么

**Comment by tiger2005** [comment]
我这边最近三场都是没有问题的。你试试看更新 Sublime Text 插件的版本？

**Comment by AshDr** [comment]
好像不太行 您sublime是什么版本呢

**Comment by tiger2005** [comment]
4152，但是感觉是 python 相关的问题

**Comment by tiger2005** [comment]
你试一下用 Postman 往这个端口以 CC 插件的 json 格式 POST 一次，看看错误信息

**Comment by tiger2005** [comment]
明天没空，得晚上才能看问题了（

**Comment by AshDr** [comment]
好 我先用postman试试吧

**Comment by AshDr** [comment]
自己debug d出来了 好像是因为

![image](https://github.com/CodeforcesContestHelper/CCHv2/assets/56424714/b4a05fbc-f37f-4758-8cac-a547de1885b8)

没有加utf-8，修改后为

![image](https://github.com/CodeforcesContestHelper/CCHv2/assets/56424714/d316c1e7-c450-4f08-8c94-354b3af7981d)

修改之后一切正常  :)

**Comment by tiger2005** [comment]
ok，我明天一起改了传到 github 和 luogu 上 :)
