### ISSUE TITLE
bug：题目界面不能显示存在子任务的题目（Win11)

### ISSUE THREAD

**Issue by gsh20040816** [CodeforcesContestHelper/CCHv2#21]
![题目界面不能显示E1E2](https://user-images.githubusercontent.com/54617983/136636588-c4add8f6-4cd2-4432-ad85-8c8db1637025.png)
![主页面可以显示E1E2](https://user-images.githubusercontent.com/54617983/136636590-52f95e1f-a100-4a3e-9ca1-87cd4fea1102.png)

**Comment by tiger2005** [comment]
@gsh20040816 最新代码已经传到 Github 的 dev 分支上。
