### ISSUE TITLE
字体中的 `'Monospace'` 是否应为 `monospace`？

### ISSUE THREAD

**Issue by Henry-ZHR** [CodeforcesContestHelper/CCHv2#37]
https://github.com/CodeforcesContestHelper/CCHv2/blob/85d75ea2348c26246d188d475dcb81bd2c6532a9/css/client.css#L19-L20

**Comment by Henry-ZHR** [comment]
（我这里 Firefox 把 `'Monospace'` fallback 到不知道什么奇奇怪怪的字体了，导致默认字体下中文有两种字形

**Comment by tiger2005** [comment]
> （我这里 Firefox 把 `'Monospace'` fallback 到不知道什么奇奇怪怪的字体了，导致默认字体下中文有两种字形

Problem Fixed.
