### ISSUE TITLE
markdown表格支持

### ISSUE THREAD

**Issue by FZ-c** [CodeforcesContestHelper/CCHv2#45]
markdown表格没有正常显示
对应的gym编号为103496。
![image](https://user-images.githubusercontent.com/26593764/149073713-ff788785-5352-4c29-8e6a-d9fa77088ea9.png)
![image](https://user-images.githubusercontent.com/26593764/149073630-1aa3b638-655f-49a6-949e-45d5ce0f9578.png)

**Comment by tiger2005** [comment]
KaTeX 似乎并不支持 align……到时候我看能不能换成 Mathjax

**Comment by tiger2005** [comment]
依赖换好了

**Comment by tiger2005** [comment]
问题已解决，请获取新版本。
