### ISSUE TITLE
多人Rating折线图

### ISSUE THREAD

**Issue by Real-king-Ph** [CodeforcesContestHelper/CCHv2#46]
这个功能似乎在很久之前就以及实现了。
将这个[代码](https://pastebin.com/PcZFDg5T)贴入油猴就可以使用了
使用：在proflie在自己rating右上角的名称上点一下，然后输入其他用户名就好

这个功能是否可以集成到 CCHv2 中呢。

类似一键获取 friend 和自己的折线统计图，然后设置开关什么的，让这个折线图像大多数工具一样可以进行一些操作。

**Comment by tiger2005** [comment]
感谢提出建议！我将会在 CCHv3 中添加功能。
