### ISSUE TITLE
“简介”中的”提交记录“页面无法正确显示提交的”In queue“状态

### ISSUE THREAD

**Issue by zwuis** [CodeforcesContestHelper/CCHv2#47]
如标题。

截图：
![)@I{@Y5XB6Z~$CDJDVJEGSB](https://user-images.githubusercontent.com/42805402/155320183-8e225102-424d-4c5f-9cf1-f894261cae96.png)

**Comment by tiger2005** [comment]
bug 主要是因为 INQ 不属于提交状态的 status，因此返回了 undefined 没有特判到。之后找个时间把最近收到的情报整理一下修出来。

**Comment by tiger2005** [comment]
看起来修好了，待会等新版本吧

**Comment by tiger2005** [comment]
问题已解决，请获取新版本。
