### ISSUE TITLE
复制和翻译

### ISSUE THREAD

**Issue by liangruichen** [CodeforcesContestHelper/CCHv2#48]
建议提交记录界面的数据和代码可以复制    
建议可以划词翻译~~来照顾我这种英语垃圾~~

**Comment by tiger2005** [comment]
> 建议提交记录界面的数据和代码可以复制 建议可以划词翻译~来照顾我这种英语垃圾~

CCHv2 不考虑此功能。

不过 CCHv3 可能会有这个增益选项（

**Comment by GuZheran** [comment]
CCHv3何时发布?

**Comment by tiger2005** [comment]
由于本人学业问题支不开时间，开发会变得缓慢

**Comment by GuZheran** [comment]
明白

**Comment by cyrxdzj** [comment]
复制代码这个，我尝试一下。

注：我不是CCHv2的官方人员，只是闲着没事干搞点事情。

**Comment by cyrxdzj** [comment]
PR已提交，请开发者审阅。

https://github.com/CodeforcesContestHelper/CCHv2/pull/57

**Comment by tiger2005** [comment]
翻译功能确认之后将不会上线。该 PR 问题讨论结束。
