### ISSUE TITLE
无法加载通过数

### ISSUE THREAD

**Issue by tzcawa** [CodeforcesContestHelper/CCHv2#50]
![](https://s1.ax1x.com/2022/04/22/LRNP4f.png)

按F12，显示

![](https://s1.ax1x.com/2022/04/22/LRNuEq.png)

然后其它的东西，估计是在队列中，也什么都加载不了/ll

**Comment by tzcawa** [comment]
源换成 `codeforc.es` 就行了，估计是 `codeforces.com` 卡了。

我的建议是失败了之后给个提示，不然很难让人知道加载失败了（

**Comment by tiger2005** [comment]
> 源换成 `codeforc.es` 就行了，估计是 `codeforces.com` 卡了。
> 
> 我的建议是失败了之后给个提示，不然很难让人知道加载失败了（

其实之前我也遇到过（

可能最近会集中一下进行小更新

**Comment by tiger2005** [comment]
问题应该是解决了

**Comment by tiger2005** [comment]
问题已解决，请获取新版本。
