### ISSUE TITLE
个人页面点击获取信息后显示网络错误

### ISSUE THREAD

**Issue by Jiamue** [CodeforcesContestHelper/CCHv2#61]

**Comment by cyrxdzj** [comment]
大概率是Codeforces炸了。

**Comment by cyrxdzj** [comment]
严格来讲，是Codeforces出了个BUG吧

**Comment by cyrxdzj** [comment]
严格来讲，是Codeforces出了个BUG吧

**Comment by cyrxdzj** [comment]
严格来讲，是Codeforces出了个BUG吧

**Comment by cyrxdzj** [comment]
@tiger2005 
我查了一下控制台，
![image](https://user-images.githubusercontent.com/63708985/185783329-a7acffea-1a0a-452e-a3d2-ee83deaec951.png)
一个玄学错误。

**Comment by cyrxdzj** [comment]
![image](https://user-images.githubusercontent.com/63708985/185783528-77497ee3-c0e9-419a-938e-51c3c88a6d73.png)
如果直接访问，有小概率得到这个页面。

**Comment by tiger2005** [comment]
充足的事实说明此时 CodeForces 寄了，CCHv2 不做处理。

**Comment by cyrxdzj** [comment]
Codeforces API已经恢复，现在可以试试了。
@tiger2005 
@Jiamue
