### ISSUE TITLE
无法显示头像

### ISSUE THREAD

**Issue by gszj2018** [CodeforcesContestHelper/CCHv2#64]
如图所示：
![图片](https://user-images.githubusercontent.com/9900631/191075716-215f4ea8-0c4b-45ae-90d9-f7a6eba6e51b.png)

初步判断问题是出在对头像URL的处理上，目前Codeforces API返回的头像URL没有协议名，形如：
```//userpic.codeforces.org/*****/title/****************.jpg```

这种情况在浏览器里是没有问题的；但是nw.js里默认协议是`chrome-extension:`，造成了图片无法加载。

**Comment by tiger2005** [comment]
我这几天看看。

**Comment by tiger2005** [comment]
有点搞不懂为啥 CodeForces 要这么弄（）

**Comment by zwuis** [comment]
> 一种简单的处理办法是直接补上 `https:` 协议，但是以后 Codeforces 又改返回 url 的话又得直接改源码。

Codeforces 已补回返回 url 中的 `https:` 协议。头像已正常显示。

**Comment by zwuis** [comment]
> > 一种简单的处理办法是直接补上 `https:` 协议，但是以后 Codeforces 又改返回 url 的话又得直接改源码。
> 
> Codeforces 已补回返回 url 中的 `https:` 协议。头像已正常显示。

现在返回 url 中又没有 `https:` 协议了……还是得识别返回 url 中是否有协议部分。

**Comment by tiger2005** [comment]
目前也只能直接判断是否加了协议.jpg
我先直接硬判断了。
