### ISSUE TITLE
个人界面右下方的题目状态为空白

### ISSUE THREAD

**Issue by zwuis** [CodeforcesContestHelper/CCHv2#65]
如图：

![06N{S}}QIECAKJZPR4D Q5O](https://user-images.githubusercontent.com/42805402/192083678-8837a2f4-338d-4f38-9d2f-f1220aae2c4e.png)

 09911f2  中没有出现此问题， 320a876（#63）中出现此问题

操作系统：Windows 10.0.19044.2006
nw.js 版本：0.59.1

**Comment by tiger2005** [comment]
我这几天看看。

**Comment by tiger2005** [comment]
请问这个问题在新版本中是一直出现还是随机出现？

**Comment by zwuis** [comment]
> 请问这个问题在新版本中是一直出现还是随机出现？

一直出现。
