### ISSUE TITLE
登录失败，显示 'csrf_token' 加载失败

### ISSUE THREAD

**Issue by Enderhz** [CodeforcesContestHelper/CCHv2#70]
<img width="646" alt="image" src="https://user-images.githubusercontent.com/103828674/202879256-2d15fc7a-ec7f-4d7d-b95c-df97de95dd97.png">
如图，最近CF好像多了好多重定向？

**Comment by n-WN** [comment]
遇到了一样的问题

**Comment by eqvpkbz** [comment]
一样的 +1

**Comment by cyrxdzj** [comment]
估计是Codeforces日爆，Codeforces偶尔会封API。

**Comment by tiger2005** [comment]
如果遇到重定向的需求（也就是无法获取 csrf_token 的情况），可以点击登录页面的右上角，在弹出的页面内进行登录。随后点击登陆的状态就可以刷新状态了。
如果这样还不行的话请在下面继续说明。

**Comment by Enderhz** [comment]
好的
（但是已经退役了，先close了吧）
