### ISSUE TITLE
登陆后名字变成undefined，且无法交题

### ISSUE THREAD

**Issue by fexla** [CodeforcesContestHelper/CCHv2#71]
![image](https://user-images.githubusercontent.com/41383116/207806790-33c3f2fc-8fec-4601-a779-cc87a3e76203.png)

**Comment by zzhqwq** [comment]
一直都有这个问题，无法使用

**Comment by caibyte** [comment]
应该还是 CF api 炸了的原因，这种情况在这条评论发布前也出现过，发布时就没问题

**Comment by tiger2005** [comment]
我先更改一下判定策略。这个大概率是网页加载失败了。
