### ISSUE TITLE
Linux 打包问题

### ISSUE THREAD

**Issue by Nikaidou-Shinku** [CodeforcesContestHelper/CCHv2#77]
Release 的时候给 Linux 打包请打 tar 包，否则会丢失包括文件权限在内的很多元信息。

**Comment by tiger2005** [comment]
目前已经换了之前的 Workflow 文件，正在重新打包这次更新。

**Comment by tiger2005** [comment]
草，没换指令内容。再等一会。

**Comment by tiger2005** [comment]
现在指令应该是对的，待会你这边下下来看看有没有压缩成功吧。

**Comment by tiger2005** [comment]
看起来是对的，先关了。
