### ISSUE TITLE
关于 Rating 预测器

### ISSUE THREAD

**Issue by hellolllllin** [CodeforcesContestHelper/CCHv2#82]
之前有人在 #73 这个 issue 提到了关于 Rating 预测器网址无法正常工作的问题，这里给一个新的预测器链接，亲测填入配置后能用，~~希望能包含在下次更新中~~：

`https://cf-predictor.wasylf.xyz/GetNextRatingServlet`

**Comment by tiger2005** [comment]
我会考虑更换默认网址，谢谢你的汇报。

**Comment by tiger2005** [comment]
在 #83 中已经更换。
