### ISSUE TITLE
无法预览 AC 代码

### ISSUE THREAD

**Issue by ckb2008** [CodeforcesContestHelper/CCHv2#86]
rt
![image](https://user-images.githubusercontent.com/99475326/229794766-dbc3c648-9031-4a7f-a34b-00434d33832d.png)
但是可以点击下面的 Copy Code 按钮复制代码。

**Comment by tiger2005** [comment]
这个情况的出现原因还在调查中，但是可以确定的是这个提交记录对应的比赛还没有结束。这个特性并不影响最主要的功能，经过衡量暂时不修复，实在抱歉。

**Comment by tiger2005** [comment]
知道原因了，indexOf 的时候多打了一个双引号导致无法检测，现在好了。
