### ISSUE TITLE
无法正常登陆

### ISSUE THREAD

**Issue by Evander-Liam** [CodeforcesContestHelper/CCHv2#88]
CF不久前加上了Cloudflare, 现在CCH2偶尔就登陆不了账号了(在赛时比较常见).
![屏幕截图 2023-04-19 101029](https://user-images.githubusercontent.com/101777683/232948442-f3497c57-2c3d-47cc-a5ff-95069bbc097e.png)
![image](https://user-images.githubusercontent.com/101777683/232948497-4b8248f3-5cce-4cc3-a3f4-961f831c4cf1.png)

**Comment by tiger2005** [comment]
CodeForces 加了反爬虫机制的话，这种情况其实对于辅助性工具是很棘手的。我尊重 CodeForces 在反爬虫方面的选择，所以不进行更新。实在抱歉。

**Comment by Evander-Liam** [comment]
> CodeForces 加了反爬虫机制的话，这种情况其实对于辅助性工具是很棘手的。我尊重 CodeForces 在反爬虫方面的选择，所以不进行更新。实在抱歉。

好的好的
