### ISSUE TITLE
在获取样例的时候和competitive companion有什么区别嘛

### ISSUE THREAD

**Issue by Kicamon** [CodeforcesContestHelper/CCHv2#89]
我用的neovim，试过了competitest.nvim和cphelper.nvim这两个插件都能够从competitive companion中获取测试样例，但是无法从cchv2中获取。

**Comment by tiger2005** [comment]
我这边安装并测试了 competitest.nvim，并没有成功复现你的问题。

**Comment by Kicamon** [comment]
好哒！谢谢虎虎～
