### ISSUE TITLE
[功能请求]自动生成API Key

### ISSUE THREAD

**Issue by szdytom** [CodeforcesContestHelper/CCHv2#96]
在登录且以填入密码的前提下，添加一个按钮允许CCH自动新增API Key.

生成API Key的接口是 `POST /settings/api`，表单字段：

```
csrf_token: "XXXX"
action: "generateKey"
newKeyName: "CCHv2"
password: "..."
```

**Comment by tiger2005** [comment]
API Key 依赖于安全的行为，而 CCHv2 目前可能还达不到这个标准。建议还是前往 CF 网站新建。
